repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace


#-   repo: https://github.com/dnephin/pre-commit-golang
#    rev: v0.5.1

#    hooks:
 #       - id: go-fmt
        #- id: go-vet
  #      - id: go-imports
#

-   repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
    -   id: go-fmt-import
    #-   id: go-vet
    #-   id: go-lint
    #- id: go-unit-tests
    #- id: gofumpt # requires github.com/mvdan/gofumpt
    #- id: go-err-check # requires github.com/kisielk/errcheck
    #- id: go-static-check # install https://staticcheck.io/docs/
    -   id: golangci-lint # requires github.com/golangci/golangci-lint
