
--

-- create db and user grant usage on it
/*
CREATE DATABASE weblink;
CREATE USER weblink PASSWORD 'weblink';
GRANT ALL PRIVILEGES ON DATABASE weblink TO weblink;
*/
-- run under weblink tables creation in that database
BEGIN;

CREATE TYPE e_role AS ENUM (
    'SUPERUSER',
    'CREATOR',
    'USER');
-- Таблица пользователей
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       uid VARCHAR (50) NOT NULL, -- ключ пользователя в токене hash(username+password+email)
                       name VARCHAR ( 50 ) NOT NULL,
                       passwd VARCHAR ( 50 ) NOT NULL,
                       email VARCHAR ( 255 ) NOT NULL,
                       created_on TIMESTAMPTZ NOT NULL,
                       last_login TIMESTAMPTZ,
                       is_active BOOL DEFAULT TRUE, -- f - удаление пользователя
                       user_role e_role NOT NULL , -- роль пользователя
                       is_balance_blocked BOOL DEFAULT FALSE, -- t - блокировка из-за отриц баланса
                       balance NUMERIC (8,2) DEFAULT 00.00, -- кошелек пользователя default = 0

                       CONSTRAINT users_uid_pkey PRIMARY KEY (id),
                       CONSTRAINT users_username_key UNIQUE (name, email),
                       CONSTRAINT users_uid_key UNIQUE (uid)

);
--- INDEX for table users
CREATE INDEX users_name_idx ON users USING btree (name) INCLUDE (is_balance_blocked);
CREATE INDEX users_uid_idx ON users USING btree (uid) INCLUDE (is_balance_blocked);

-- Таблица данных ссылок
CREATE TABLE users_data (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY, -- ключ
                            user_id BIGINT NOT NULL,
                            uid VARCHAR (50) NOT NULL,
                            url VARCHAR (255) NOT NULL, -- УРЛ
                            short_url VARCHAR (64) NOT NULL UNIQUE , -- короткая ссылка -- inline constraints самые сильные
                            date_time TIMESTAMPTZ, -- дата создания или изменения
                            is_active BOOL DEFAULT TRUE, -- f - удалена
                            redirs INT DEFAULT 0, -- cчетчик переходов по ссылке
                            CONSTRAINT users_data_id_pkey PRIMARY KEY (id),
    -- для вставкоапдейта значений по уникальному ключу 2 столбцов:
                            CONSTRAINT users_data_shorturl_user_id_keys UNIQUE (short_url, user_id),
                            CONSTRAINT fk_user
                                FOREIGN KEY(user_id) -- FK на пользователя
                                    REFERENCES users(id)
                                    ON DELETE CASCADE
);
--- INDEX for table user_data
CREATE INDEX users_data_short_url_idx ON users_data USING btree (short_url) INCLUDE (user_id);
CREATE INDEX users_data_date_time_idx ON users_data USING btree (date_time);

--- Таблица финансовых транзакций
CREATE TABLE users_transactions (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    date_time TIMESTAMPTZ NOT NULL, -- дата транз
                                    user_id_from BIGINT NOT NULL, -- кто
                                    user_id_to BIGINT NOT NULL,  -- кому
                                    amount NUMERIC (8,2) NOT NULL, -- сколько
                                    description VARCHAR (128), -- описание операции
                                    successful BOOL NOT NULL,
                                    CONSTRAINT users_transactions_id_pkey PRIMARY KEY (id),
                                    CONSTRAINT fk_user_from
                                        FOREIGN KEY(user_id_from) -- FK на пользователя a
                                            REFERENCES users(id)
                                            ON DELETE CASCADE,
                                    CONSTRAINT fk_user_to
                                        FOREIGN KEY(user_id_to) -- FK на пользователя б
                                            REFERENCES users(id)
                                            ON DELETE CASCADE
);
--- INDEX for table users_transactions
CREATE INDEX users_transactions_datetime_idx ON users_transactions USING btree (date_time);

COMMIT;
