name: My Go

on:
  push:
    branches: [ kurs ]
  pull_request:
    branches: [ kurs ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2

  CheckAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3

    - name: Test
      run: go test ./kurs/app1/filter

    - name: Install GolangCI-lint
      run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.39.0

    - name: Install Golint
      run: go get -u golang.org/x/lint/golint

    - name: Check Golint
      run: golint $(go list ./kurs/app1/... | grep -v /vendor/)

    - name: Check Golangci-lint
      run: golangci-lint run ./kurs/app1/...
