name: My Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2

  CheckAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.6

    - name: Test API
      run: cd web-link && go test ./...

    - name: Install GolangCI-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Install Golint
      run: go install -u golang.org/x/lint/golint@latest

    - name: Check Golint
      run: cd web-link && golint $(go list ./... | grep -v /vendor/)

    - name: Check Golangci-lint
      run: cd web-link && golangci-lint run ./...
